name: force_update_helper
description: "A package for showing a force update prompt that is controlled remotely."
version: 0.2.2
homepage: https://codewithandrea.com/
repository: https://github.com/bizz84/force_update_helper
platforms:
  android:
  ios:

environment:
  sdk: ^3.5.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^9.0.0
  pub_semver: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
